name: LastApi
version: 1.0.0
main: net.jetluna.api.LastApi
api-version: 1.21
database:
  host: "127.0.0.1"
  port: "3306"
  name: "last_engine"
  user: "root"
  password: ""
commands:
  setrank:
    description: Выдать ранг игроку
    usage: /setrank <player> <rank>
    permission: last.admin
  kick:
    description: Кикнуть игрока
    usage: /kick <player> [reason]
  mute:
    description: Замутить игрока
    usage: /mute <player> <time> [reason]
  ban:
    description: Забанить игрока
    usage: /ban <player> <time> [reason]
  unmute:
    description: Снять мут
    usage: /unmute <player>
  unban:
    description: Снять бан
    usage: /unban <player>
  history:
    description: История наказаний
    usage: /history <player>
  banlist:
    description: Список активных банов
    usage: /banlist
  lang:
    description: Сменить язык
    usage: /lang <ru/en/ua>
  sc:
    description: Чат для персонала
    usage: /sc <сообщение>
    aliases: [ staffchat ]
  dc:
    description: Чат для донатеров
    usage: /dc <сообщение>
    aliases: [ donorchat ]
  msg:
    description: Личное сообщение
    usage: /msg <player> <message>
    aliases: [ tell, w ]
  r:
    description: Быстрый ответ
    usage: /r <message>
    aliases: [ reply ]
  eco:
    description: Управление экономикой
    usage: /eco <give|set> <player> <coins|emeralds> <amount>
  stream:
    description: Управление стримами
    usage: /stream <add|stop> <ссылка>
  streams:
    description: Список активных стримов
    usage: /streams
  report:
    description: Отправить жалобу на игрока
    usage: /report <ник> <причина>
  reports:
    description: Просмотр активных жалоб
    usage: /reports
  friend:
    description: Система друзей
    aliases: [f, friends]
    usage: /friend <add|accept|deny|remove> <ник>
  skin:
    description: Установить скин лицензионного игрока
    usage: /skin <ник>
  skins:
    description: Меню истории ваших скинов
    aliases: [ skinhistory ]