name: LastAuth
version: 1.0.0
main: net.jetluna.auth.AuthPlugin
api-version: 1.21
commands:
  reg:
  l:
  code:
  heal:                # <--- ДОБАВЛЯЕМ
    description: Restore health
    permission: last.admin
  setauthspawn:
    description: Set spawn
    permission: last.admin