name: LastLobby
version: 1.0.0
main: net.jetluna.lobby.LobbyPlugin
api-version: 1.21
depend:
  - LastApi
  - Citizens
commands:
  lobby:
    description: На спавн
  setlobbyspawn:
    description: Сет спавн
    permission: last.admin
  # ДОБАВЬ ВОТ ЭТО:
  setnpc:
    description: Поставить NPC
    permission: last.admin